/**
 * ORBX MEDIA - AI Video Production Reels Central Data & Sync Controller
 * Generated by Agent Studio for live deployment across all devices.
 */

const DEFAULT_REELS = [
    {
        "id": "CW33Gn8cU8w",
        "title": "Cybernetic Vision",
        "category": "Generative Cinema",
        "poster": "https://img.youtube.com/vi/CW33Gn8cU8w/hqdefault.jpg"
    },
    {
        "id": "bb1mzI0MaPE",
        "title": "Neural Worldscapes",
        "category": "Virtual Cinematography",
        "poster": "https://img.youtube.com/vi/bb1mzI0MaPE/hqdefault.jpg"
    },
    {
        "id": "cbFd-xK_hmc",
        "title": "Fluid Morphologies",
        "category": "Stylized Motion AI",
        "poster": "https://img.youtube.com/vi/cbFd-xK_hmc/hqdefault.jpg"
    },
    {
        "id": "-NAf_Bth1Q0",
        "title": "Synthetic Humanoids",
        "category": "Character Concept AI",
        "poster": "https://img.youtube.com/vi/-NAf_Bth1Q0/hqdefault.jpg"
    },
    {
        "id": "iwWcWjnj020",
        "title": "Cinematic AI Showcase",
        "category": "Creative Commercial AI",
        "poster": "https://img.youtube.com/vi/iwWcWjnj020/hqdefault.jpg"
    },
    {
        "id": "WhaOZ298OqI",
        "title": "Dimensions of Light",
        "category": "Future Film Aesthetics",
        "poster": "https://img.youtube.com/vi/WhaOZ298OqI/hqdefault.jpg"
    },
    {
        "id": "qRqTHi2KHPw",
        "title": "Ai Presentation Model",
        "category": "Generative Cinema",
        "poster": "https://img.youtube.com/vi/qRqTHi2KHPw/hqdefault.jpg"
    }
];

// Curated library of presets agents can choose to add/swap into the reels section
const PRESET_REELS = [
    {
        "id": "CW33Gn8cU8w",
        "title": "Cybernetic Vision",
        "category": "Generative Cinema",
        "poster": "https://img.youtube.com/vi/CW33Gn8cU8w/hqdefault.jpg"
    },
    {
        "id": "bb1mzI0MaPE",
        "title": "Neural Worldscapes",
        "category": "Virtual Cinematography",
        "poster": "https://img.youtube.com/vi/bb1mzI0MaPE/hqdefault.jpg"
    },
    {
        "id": "cbFd-xK_hmc",
        "title": "Fluid Morphologies",
        "category": "Stylized Motion AI",
        "poster": "https://img.youtube.com/vi/cbFd-xK_hmc/hqdefault.jpg"
    },
    {
        "id": "-NAf_Bth1Q0",
        "title": "Synthetic Humanoids",
        "category": "Character Concept AI",
        "poster": "https://img.youtube.com/vi/-NAf_Bth1Q0/hqdefault.jpg"
    },
    {
        "id": "iwWcWjnj020",
        "title": "Cinematic AI Showcase",
        "category": "Creative Commercial AI",
        "poster": "https://img.youtube.com/vi/iwWcWjnj020/hqdefault.jpg"
    },
    {
        "id": "WhaOZ298OqI",
        "title": "Dimensions of Light",
        "category": "Future Film Aesthetics",
        "poster": "https://img.youtube.com/vi/WhaOZ298OqI/hqdefault.jpg"
    },
    {
        "id": "d96wv11ExBo",
        "title": "Neo-Tokyo Cyberpunk",
        "category": "Sci-Fi Realism AI",
        "poster": "https://img.youtube.com/vi/d96wv11ExBo/hqdefault.jpg"
    },
    {
        "id": "YV4r_rCg0e8",
        "title": "AI Luxury Commercial",
        "category": "Brand Aesthetics",
        "poster": "https://img.youtube.com/vi/YV4r_rCg0e8/hqdefault.jpg"
    },
    {
        "id": "Sdpv7q2V2sU",
        "title": "Cosmic Odyssey",
        "category": "Space Exploration AI",
        "poster": "https://img.youtube.com/vi/Sdpv7q2V2sU/hqdefault.jpg"
    }
];

const STORAGE_KEY = 'orbx_custom_reels';
const CLOUD_SYNC_KEY = 'orbx_cloud_sync_url';

function extractYouTubeId(urlOrId) {
    if (!urlOrId) return '';
    const trimmed = String(urlOrId).trim();
    if (/^[a-zA-Z0-9_-]{11}$/.test(trimmed)) return trimmed;
    const shortsMatch = trimmed.match(/\/shorts\/([a-zA-Z0-9_-]{11})/);
    if (shortsMatch && shortsMatch[1]) return shortsMatch[1];
    const youtuMatch = trimmed.match(/youtu\.be\/([a-zA-Z0-9_-]{11})/);
    if (youtuMatch && youtuMatch[1]) return youtuMatch[1];
    const watchMatch = trimmed.match(/[?&]v=([a-zA-Z0-9_-]{11})/);
    if (watchMatch && watchMatch[1]) return watchMatch[1];
    const embedMatch = trimmed.match(/\/embed\/([a-zA-Z0-9_-]{11})/);
    if (embedMatch && embedMatch[1]) return embedMatch[1];
    return trimmed;
}

function getActiveReels() {
    try {
        const stored = localStorage.getItem(STORAGE_KEY);
        if (stored) {
            const parsed = JSON.parse(stored);
            if (Array.isArray(parsed) && parsed.length > 0) return parsed;
        }
    } catch (e) {
        console.warn('Error reading stored reels:', e);
    }
    return DEFAULT_REELS;
}

function saveActiveReels(reels) {
    try {
        localStorage.setItem(STORAGE_KEY, JSON.stringify(reels));
        window.dispatchEvent(new CustomEvent('orbx_reels_updated', { detail: reels }));
        return true;
    } catch (e) {
        console.error('Error saving reels:', e);
        return false;
    }
}

function resetActiveReels() {
    try {
        localStorage.removeItem(STORAGE_KEY);
        window.dispatchEvent(new CustomEvent('orbx_reels_updated', { detail: DEFAULT_REELS }));
        return DEFAULT_REELS;
    } catch (e) {
        console.error('Error resetting reels:', e);
        return DEFAULT_REELS;
    }
}

/**
 * Generates raw HTML for reels grid to bake directly into HTML files or inject dynamically.
 */
function generateReelsHtml(customReels, isSubgalleryPage = false) {
    const list = customReels || (typeof getActiveReels === 'function' ? getActiveReels() : DEFAULT_REELS);
    const totalCount = list.length;
    let html = '';
    list.forEach((reel, index) => {
        const numStr = String(index + 1).padStart(2, '0');
        const totalStr = String(totalCount).padStart(2, '0');
        const videoId = extractYouTubeId(reel.id);
        const titleSafe = (reel.title || ('AI Reel ' + numStr)).replace(/"/g, '&quot;');
        const categorySafe = (reel.category || 'Generative Cinema').replace(/"/g, '&quot;');
        const posterUrl = reel.poster || ('https://img.youtube.com/vi/' + videoId + '/hqdefault.jpg');
        const clickHandler = isSubgalleryPage
            ? "openAiReelModal('" + videoId + "', '" + titleSafe.replace(/'/g, "\\'") + "')"
            : "openReelFullscreen('" + videoId + "', '" + titleSafe.replace(/'/g, "\\'") + "')";
        const revealClass = isSubgalleryPage ? ' reveal' : '';

        html += `
                <!-- Reel ${index + 1} -->
                <div class="ai-reel-box glass-panel${revealClass}" data-video-id="${videoId}"
                    data-video-title="${titleSafe}" data-index="${index}"
                    onclick="${clickHandler}">
                    <div class="ai-reel-player-container">
                        <div class="ai-reel-player-embed" id="aiPlayer${index}">
                            <iframe id="aiReelIframe${index}" loading="lazy"
                                src="https://www.youtube-nocookie.com/embed/${videoId}?autoplay=1&mute=1&controls=0&loop=1&playlist=${videoId}&playsinline=1&modestbranding=1&rel=0&iv_load_policy=3&disablekb=1&enablejsapi=1"
                                title="${titleSafe}"
                                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                                allowfullscreen></iframe>
                        </div>
                        <div class="ai-reel-poster" style="background-image: url('${posterUrl}');"></div>
                        <div class="ai-reel-overlay">
                            <div class="ai-reel-top-bar">
                                <span class="ai-reel-num">${numStr} / ${totalStr}</span>
                                <span class="ai-slowmo-pill"><span class="slowmo-pulse"></span> 0.5x Slow-Mo</span>
                            </div>
                            <div class="ai-reel-bottom-info">
                                <span class="ai-reel-category">${categorySafe}</span>
                                <h4 class="ai-reel-title">${titleSafe}</h4>
                                <span class="ai-reel-prompt-tag"><i class="fas fa-play"></i> Tap to Play with Sound</span>
                            </div>
                        </div>
                    </div>
                </div>`;
    });
    return html;
}

function renderReelsGrid(selector = '.ai-reels-grid', isSubgalleryPage = false) {
    const gridContainer = document.querySelector(selector);
    if (!gridContainer) return;
    const reels = getActiveReels();
    gridContainer.innerHTML = generateReelsHtml(reels, isSubgalleryPage);
}

/**
 * Standalone JavaScript generator for reels-data.js
 */
function generateReelsDataJsContent(customReels) {
    const list = customReels || (typeof getActiveReels === 'function' ? getActiveReels() : DEFAULT_REELS);
    const formatted = JSON.stringify(list, null, 4);
    const presets = typeof PRESET_REELS !== 'undefined' ? PRESET_REELS : list;
    const presetsFormatted = JSON.stringify(presets, null, 4);

    return `/**
 * ORBX MEDIA - AI Video Production Reels Central Data & Sync Controller
 * Generated by Agent Studio for live deployment across all devices.
 */

const DEFAULT_REELS = ${formatted};

// Curated library of presets agents can choose to add/swap into the reels section
const PRESET_REELS = ${presetsFormatted};

const STORAGE_KEY = 'orbx_custom_reels';
const CLOUD_SYNC_KEY = 'orbx_cloud_sync_url';

${extractYouTubeId.toString()}

${getActiveReels.toString()}

${saveActiveReels.toString()}

${resetActiveReels.toString()}

${generateReelsHtml.toString()}

${renderReelsGrid.toString()}

${generateReelsDataJsContent.toString()}

// Global exposure
window.DEFAULT_REELS = DEFAULT_REELS;
window.PRESET_REELS = PRESET_REELS;
window.STORAGE_KEY = STORAGE_KEY;
window.CLOUD_SYNC_KEY = CLOUD_SYNC_KEY;
window.extractYouTubeId = extractYouTubeId;
window.getActiveReels = getActiveReels;
window.saveActiveReels = saveActiveReels;
window.resetActiveReels = resetActiveReels;
window.generateReelsHtml = generateReelsHtml;
window.renderReelsGrid = renderReelsGrid;
window.generateReelsDataJsContent = generateReelsDataJsContent;
`;
}

// Global exposure
window.DEFAULT_REELS = DEFAULT_REELS;
window.PRESET_REELS = PRESET_REELS;
window.STORAGE_KEY = STORAGE_KEY;
window.CLOUD_SYNC_KEY = CLOUD_SYNC_KEY;
window.extractYouTubeId = extractYouTubeId;
window.getActiveReels = getActiveReels;
window.saveActiveReels = saveActiveReels;
window.resetActiveReels = resetActiveReels;
window.generateReelsHtml = generateReelsHtml;
window.renderReelsGrid = renderReelsGrid;
window.generateReelsDataJsContent = generateReelsDataJsContent;
